@extends('layouts.test')
 
@section('body')
 
<h1>NX Scanner test</h1>
<label class="checkbox">
    <input type="checkbox" id="useDefaultPrinter" /> <strong>Use default printer</strong> or...
</label>
<div id="loadPrinters">
<br />
    WebClientPrint can detect the installed printers in your machine.
<br />
<input type="button" onclick="javascript:jsWebClientPrint.getPrinters();" value="Load installed printers..." />
                 
<br /><br />
</div>
<div id="installedPrinters" style="visibility:hidden">
<br />
<label for="installedPrinterName">Select an installed Printer:</label>
<select name="installedPrinterName" id="installedPrinterName"></select>
</div>

<div class="col-md-4">
    <div class="form-group">
        <label>Number of labels to print</label>
        <select class="form-control" name="labels" id="labels">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select>
    </div>
    <div class="form-group">
        <label>Sensor</label>
        <input type="text" class="form-control" id="sensor" name="sensor">
    </div>
    <div class="form-group">
        <label>Radio</label>
        <input type="text" class="form-control" id="radio" name="radio">
    </div>
    <div class="form-group">
        <label>Fix. controller</label>
        <input type="text" class="form-control" id="controller" name="controller">
    </div>

    <input type="button" onclick="printLabel();" value="Print Label ..." class="btn btn-primary"/>
</div>
       
@endsection
 
@section('scripts')
 
<script type="text/javascript">
    var wcppGetPrintersTimeout_ms = 10000; //10 sec
    var wcppGetPrintersTimeoutStep_ms = 500; //0.5 sec
 
    function wcpGetPrintersOnSuccess(){
        // Display client installed printers
        if(arguments[0].length > 0){
            var p=arguments[0].split("|");
            var options = '';
            for (var i = 0; i < p.length; i++) {
                options += '<option>' + p[i] + '</option>';
            }
            $('#installedPrinters').css('visibility','visible');
            $('#installedPrinterName').html(options);
            $('#installedPrinterName').focus();
            $('#loadPrinters').hide();                                                        
        }else{
            alert("No printers are installed in your system.");
        }
    }
 
    function wcpGetPrintersOnFailure() {
        // Do something if printers cannot be got from the client
        alert("No printers are installed in your system.");
    }

    function printLabel(){
            javascript:jsWebClientPrint.print('useDefaultPrinter=' + $('#useDefaultPrinter').attr('checked') + '&printerName=' + $('#installedPrinterName').val() + '&sensor=' + $('#sensor').val() + '&radio=' + $('#radio').val() + '&controller=' + $('#controller').val() + '&labels=' + $('#labels').val());
    }
</script>
 
 
{!! 
 
// Register the WebClientPrint script code
// The $wcpScript was generated by PrintZPLController@index
 
$wcpScript;
 
!!}
 
@endsection